# Generated by Django 4.1.7 on 2023-04-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_codigoqr_titleqr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoqr',
            name='imageQr',
        ),
        migrations.AddField(
            model_name='codigoqr',
            name='linkQr',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
