# Generated by Django 4.1.7 on 2023-04-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_remove_codigoqr_imageqr_codigoqr_linkqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='imgQr',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
