# Generated by Django 4.1.7 on 2023-04-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_codigoqr_imgqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoqr',
            name='authorQr',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
