# Generated by Django 4.1.7 on 2023-04-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_codigoqr_authorqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='authorQr',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
